DROP TABLE BANCO.PRODUTO CASCADE;

CREATE TABLE BANCO.PRODUTO
(id             BIGINT(20)   NOT NULL AUTO_INCREMENT,
 NOME           VARCHAR(30)  NOT NULL,
 LANCE_MINIMO   NUMERIC(8,2) NOT NULL,
 DATA_CADASTRO  DATE         NOT NULL,
 DATA_VENDA     DATE,
 PRIMARY KEY(id)
)
ENGINE = INNODB;

INSERT INTO BANCO.PRODUTO(NOME, LANCE_MINIMO, DATA_CADASTRO)
VALUES('TV SAMSUNG 20 POL', 2000, NOW());

INSERT INTO BANCO.PRODUTO(NOME, LANCE_MINIMO, DATA_CADASTRO)
VALUES('TV SAMSUNG 22 POL', 2500, NOW());

COMMIT;
